/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dataservice.PersistenciaPersonagem;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Personagem;
import resources.ItemTableModel;
import resources.PersonagemTableModel;

/**
 *
 * @author felipe_baumgartel
 */
public class CadPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form CadJogador
     */
    public CadPersonagem() {
        initComponents();
        setTitle("Cadastro de Personagem");
        setLocationRelativeTo(null);
        txId.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txVida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txNivel = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txAtaque = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txExperiencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txDefesa = new javax.swing.JTextField();
        txDinheiro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        btSalvar.setBackground(new java.awt.Color(0, 204, 204));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar);

        btVoltar.setBackground(new java.awt.Color(0, 204, 204));
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltar);

        btDeletar.setBackground(new java.awt.Color(0, 204, 204));
        btDeletar.setText("Deletar");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btDeletar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        btNovo.setBackground(new java.awt.Color(0, 204, 204));
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btNovo);

        btCancelar.setBackground(new java.awt.Color(0, 204, 204));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btCancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        txVida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txVidaKeyTyped(evt);
            }
        });

        jLabel4.setText("Vida:");

        jLabel3.setText("Nível:");

        txNivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNivelKeyTyped(evt);
            }
        });

        txNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNomeKeyTyped(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel1.setText("ID:");

        txId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txIdKeyTyped(evt);
            }
        });

        jLabel5.setText("Defesa:");

        txAtaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txAtaqueKeyTyped(evt);
            }
        });

        jLabel6.setText("Ataque:");

        txExperiencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txExperienciaKeyTyped(evt);
            }
        });

        jLabel7.setText("Experiência:");

        txDefesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txDefesaKeyTyped(evt);
            }
        });

        txDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txDinheiroKeyTyped(evt);
            }
        });

        jLabel8.setText("Dinheiro:");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txNivel)
                    .addComponent(txVida)
                    .addComponent(txNome)
                    .addComponent(txId, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txDefesa)
                    .addComponent(txExperiencia)
                    .addComponent(txAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txDinheiro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        habilitarComponentes();
        limparCampos();
        txId.requestFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        desabilitarComponentes();
        limparCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (txId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem um codigo");
        } else if (txNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem um nome");
        } else if (txNivel.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem um nível");
        } else if (txVida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem uma vida");
        } else if (txAtaque.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem um ataque");
        } else if (txDefesa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem uma defesa");
        } else if (txExperiencia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem uma experiência");
        } else if (txDinheiro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não pode gravar sem um dinheiro");
        } else {
            PersistenciaPersonagem.save(CriarPersonagem());
            JOptionPane.showMessageDialog(null, "Personagem cadastrado com Sucesso");
            atualizarTabela();
            limparCampos();
            desabilitarComponentes();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txVidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txVidaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || c == '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txVidaKeyTyped

    private void txNivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNivelKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || c == '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txNivelKeyTyped

    private void txNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNomeKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txNomeKeyTyped

    private void txIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txIdKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txIdKeyTyped

    private void txAtaqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAtaqueKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || c == '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txAtaqueKeyTyped

    private void txExperienciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txExperienciaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || c == '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txExperienciaKeyTyped

    private void txDefesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDefesaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || c == '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txDefesaKeyTyped

    private void txDinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDinheiroKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' || c == '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txDinheiroKeyTyped

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        Personagem a = ptm.getValueAT(jTable1.getSelectedRow());
        PersistenciaPersonagem.delete(a);
        JOptionPane.showMessageDialog(null, "Personagem deletado com sucesso");
        atualizarTabela();
    }//GEN-LAST:event_btDeletarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() > 1) {

            Personagem a = ptm.getValueAT(jTable1.getSelectedRow());
            recuperarPersonagem(a);
            txId.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    private void habilitarComponentes() {
        txId.setEnabled(true);
        txNome.setEnabled(true);
        txNivel.setEnabled(true);
        txVida.setEnabled(true);
        txAtaque.setEnabled(true);
        txDefesa.setEnabled(true);
        txExperiencia.setEnabled(true);
        txDinheiro.setEnabled(true);
        btCancelar.setEnabled(true);
        btSalvar.setEnabled(true);
    }

    private void desabilitarComponentes() {
        txId.setEnabled(false);
        txNome.setEnabled(false);
        txNivel.setEnabled(false);
        txVida.setEnabled(false);
        txAtaque.setEnabled(false);
        txDefesa.setEnabled(false);
        txExperiencia.setEnabled(false);
        txDinheiro.setEnabled(false);
        btCancelar.setEnabled(false);
        btSalvar.setEnabled(false);

    }

    private Personagem CriarPersonagem() {
        int Id = Integer.parseInt(txId.getText());
        String Nome = txNome.getText();
        int Nivel = Integer.parseInt(txNivel.getText());
        int Vida = Integer.parseInt(txVida.getText());
        int Ataque = Integer.parseInt(txAtaque.getText());
        int Defesa = Integer.parseInt(txDefesa.getText());
        double Experiencia = Double.parseDouble(txExperiencia.getText());
        double Dinheiro = Double.parseDouble(txDinheiro.getText());

        Personagem personagem1 = new Personagem(Id, Nome, Nivel, Vida, Ataque, Defesa, Experiencia, Dinheiro);

        return personagem1;
    }

    private void limparCampos() {
        txId.setText("");
        txNome.setText("");
        txNivel.setText("");
        txVida.setText("");
        txAtaque.setText("");
        txDefesa.setText("");
        txExperiencia.setText("");
        txDinheiro.setText("");

        btCancelar.removeAll();
        btSalvar.removeAll();
    }

    private TableModel carregarTabela() {
        List<Personagem> lista = PersistenciaPersonagem.list();
        ptm = new PersonagemTableModel(lista);
        return ptm;
    }

    private void atualizarTabela() {
        jTable1.setModel(carregarTabela());
    }

    private void recuperarPersonagem(Personagem a) {
        habilitarComponentes();
        txId.setText(String.valueOf(a.getId()));
        txNome.setText(a.getNome());
        txNivel.setText(String.valueOf(a.getNivel()));
        txVida.setText(String.valueOf(a.getVida()));
        txAtaque.setText(String.valueOf(a.getAtaque()));
        txDefesa.setText(String.valueOf(a.getDefesa()));
        txExperiencia.setText(String.valueOf(a.getExperiencia()));
        txDinheiro.setText(String.valueOf(a.getDinheiro()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txAtaque;
    private javax.swing.JTextField txDefesa;
    private javax.swing.JTextField txDinheiro;
    private javax.swing.JTextField txExperiencia;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txNivel;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txVida;
    // End of variables declaration//GEN-END:variables
Personagem personagem;
    private PersonagemTableModel ptm;
}
